const COLORS = {
  TOAST_BROWN: '#C09A6B',
  PRIMARY_DARK: '#1F1F1F',
  PRIMARY_LIGHT: '#F2EDE4',
  ACCENT: '#FF8B43',
  SECONDARY_ACCENT: '#8DAA9D',
  BACKGROUND: '#D9C8B0',
};

export default COLORS;
